import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, ArrowRight, Info, MapPin, Ship } from 'lucide-react';
import Seo from '../../components/Seo';
import PortQuoteForm from '../../components/PortQuoteForm';
import { allPorts } from '../../data/portData';

export default function PortDetail() {
  const { slug } = useParams<{ slug: string }>();
  const port = allPorts.find((item) => item.slug === slug);
  if (!port) return <section className="container-carrgo py-24 text-center"><h1 className="text-3xl font-bold text-gray-900">Port not found</h1><p className="mt-3 text-gray-600">This port is not included in Carrgo’s 17-port evidence coverage.</p><Link to="/resources/port-congestion-tracker/" className="mt-6 inline-flex items-center gap-2 rounded-lg bg-[#1A6DFF] px-5 py-3 font-semibold text-white"><ArrowLeft className="h-4 w-4" /> View port evidence</Link></section>;

  return <>
    <Seo title={`${port.port} Port Status Evidence | Carrgo`} description={`Evidence-led ${port.port} port status page. Current waiting times, vessel queues, berth utilisation, scores and forecasts remain unknown unless supported by dated primary measurements.`} keywords={`${port.port} port status, ${port.port} port notices, ${port.port} shipping disruption, ${port.port} freight quote`} canonical={`https://www.carrgo.co.uk/ports/${port.slug}/`} />
    <div className="xl:pr-[360px]">
      <section className="bg-[#1A6DFF] py-16 text-white lg:py-24" aria-labelledby="port-title"><div className="container-carrgo"><Link to="/resources/port-congestion-tracker/" className="mb-6 inline-flex items-center gap-2 text-sm font-semibold text-blue-100 hover:text-white"><ArrowLeft className="h-4 w-4" /> Back to port evidence</Link><div className="flex items-start gap-4"><Ship className="mt-1 h-10 w-10 shrink-0" aria-hidden="true" /><div><p className="mb-2 text-sm font-semibold uppercase tracking-wider text-blue-100">Port evidence</p><h1 id="port-title" className="text-4xl font-bold md:text-5xl">{port.port} port status</h1><p className="mt-4 flex items-center gap-2 text-blue-50"><MapPin className="h-4 w-4" aria-hidden="true" /> {port.region}, {port.country}</p></div></div></div></section>
      <section className="bg-white py-12 lg:py-16" aria-labelledby="measurement-status"><div className="container-carrgo"><div className="max-w-4xl rounded-2xl border border-amber-200 bg-amber-50 p-6 md:p-8"><div className="flex gap-4"><Info className="mt-1 h-7 w-7 shrink-0 text-amber-700" aria-hidden="true" /><div><h2 id="measurement-status" className="text-2xl font-bold text-gray-900">Current congestion measurements: unknown</h2><p className="mt-3 leading-relaxed text-gray-700">Carrgo has no comparable, timestamped primary measurement for {port.port} port-wide waiting time, vessel queues, berth utilisation or congestion. Unknown does not mean that operations are normal.</p><p className="mt-3 leading-relaxed text-gray-700">Any dated local operating or weather notices are listed in the main tracker with their source, publication date, check time, confidence and limitations.</p></div></div></div></div></section>
      <section className="bg-[#F8FAFC] py-12 lg:py-16" aria-labelledby="before-booking"><div className="container-carrgo max-w-5xl"><h2 id="before-booking" className="text-2xl font-bold text-gray-900">Questions to confirm before booking or collection</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{['Is the vessel booking and terminal receiving window confirmed?','Are gate-in, release and collection appointments available?','Does a dated local notice affect the relevant berth, lock or access route?','Has the carrier issued a shipment-specific schedule or cut-off change?','Are customs documents, commodity codes and importer details complete?','What free time and demurrage or detention terms apply to this booking?'].map((question) => <p key={question} className="rounded-xl border border-gray-200 bg-white p-5 text-gray-700">{question}</p>)}</div></div></section>
      <section className="bg-white py-12" aria-labelledby="sources-method"><div className="container-carrgo max-w-4xl"><h2 id="sources-method" className="text-2xl font-bold text-gray-900">Sources and limitations</h2><p className="mt-3 leading-relaxed text-gray-700">The Carrgo tracker is a public-source evidence review, not an AIS or terminal operating feed. A local closure, dredging campaign or sea-area forecast is not converted into a numerical congestion score or delay estimate.</p><div className="mt-6 flex flex-wrap gap-3"><Link to="/resources/port-congestion-tracker/" className="inline-flex items-center gap-2 rounded-lg bg-[#1A6DFF] px-5 py-3 font-semibold text-white">Check dated evidence <ArrowRight className="h-4 w-4" /></Link><Link to="/resources/uk-port-congestion-report/" className="rounded-lg border border-gray-300 px-5 py-3 font-semibold text-gray-800">Read the weekly report</Link><Link to="/tools/port-comparison/" className="rounded-lg border border-gray-300 px-5 py-3 font-semibold text-gray-800">Compare evidence coverage</Link></div></div></section>
    </div>
    <PortQuoteForm title={`Ask about your shipment through ${port.port}`} destination={port.port} sourcePage={`/ports/${port.slug}/`} />
  </>;
}
